/*
 * generated by Xtext
 */
package org.modelexecution.operationalsemantics.ui.contentassist

import org.modelexecution.operationalsemantics.ui.contentassist.AbstractActivityDiagramProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ActivityDiagramProposalProvider extends AbstractActivityDiagramProposalProvider {
}
