<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="merge" nsURI="test.merge" nsPrefix="merge">
  <eClassifiers xsi:type="ecore:EClass" name="Clazz">
    <eOperations name="operation" eType="#//Clazz"/>
    <eOperations name="operation2">
      <eParameters name="param" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Clazz"/>
  </eClassifiers>
</ecore:EPackage>
