<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testmerge" nsURI="http://org.melange.test/" nsPrefix="testmerge">
  <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="#//SuperA">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toB" eType="#//B" eOpposite="#//B/toA"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B">
    <eOperations name="getA" eType="#//A">
      <eParameters name="paramB" eType="#//B"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toA" eType="#//A" eOpposite="#//A/toB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C"/>
  <eClassifiers xsi:type="ecore:EClass" name="AA" eSuperTypes="#//A"/>
  <eClassifiers xsi:type="ecore:EClass" name="AAA" eSuperTypes="#//AA">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toC" eType="#//C" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperA"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubB" eSuperTypes="#//B"/>
</ecore:EPackage>
