/*
 * generated by Xtext
 */
package org.xtext.lua.ui.contentassist

import org.xtext.lua.ui.contentassist.AbstractLuaProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class LuaProposalProvider extends AbstractLuaProposalProvider {
}
