/*
 * generated by Xtext 2.9.2
 */
package fr.inria.diverse.serializer;

import com.google.inject.Inject;
import fr.inria.diverse.services.MiniFSMGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class MiniFSMSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MiniFSMGrammarAccess grammarAccess;
	protected AbstractElementAlias match_TermInt_LeftParenthesisKeyword_2_0_a;
	protected AbstractElementAlias match_TermInt_LeftParenthesisKeyword_2_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MiniFSMGrammarAccess) access;
		match_TermInt_LeftParenthesisKeyword_2_0_a = new TokenAlias(true, true, grammarAccess.getTermIntAccess().getLeftParenthesisKeyword_2_0());
		match_TermInt_LeftParenthesisKeyword_2_0_p = new TokenAlias(true, false, grammarAccess.getTermIntAccess().getLeftParenthesisKeyword_2_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_TermInt_LeftParenthesisKeyword_2_0_a.equals(syntax))
				emit_TermInt_LeftParenthesisKeyword_2_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_TermInt_LeftParenthesisKeyword_2_0_p.equals(syntax))
				emit_TermInt_LeftParenthesisKeyword_2_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) name=EString
	 *     (rule start) (ambiguity) value=EInt
	 *     (rule start) (ambiguity) {Divide.left=}
	 *     (rule start) (ambiguity) {Minus.left=}
	 *     (rule start) (ambiguity) {Multiply.left=}
	 *     (rule start) (ambiguity) {Plus.left=}
	 */
	protected void emit_TermInt_LeftParenthesisKeyword_2_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) {Divide.left=}
	 *     (rule start) (ambiguity) {Minus.left=}
	 *     (rule start) (ambiguity) {Multiply.left=}
	 *     (rule start) (ambiguity) {Plus.left=}
	 */
	protected void emit_TermInt_LeftParenthesisKeyword_2_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
