/*
 * generated by Xtext
 */
package org.xtext.lua;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LuaRuntimeModule extends org.xtext.lua.AbstractLuaRuntimeModule {

}
