package fr.inria.diverse.melange.validation

class MelangeValidationConstants
{
	public static final String ELEMENT_NAME_EMPTY = "ELEMENT_NAME_EMPTY"
	public static final String ELEMENT_NAME_DUPLICATED = "ELEMENT_NAME_DUPLICATED"
	public static final String MODELTYPE_ECORE_EMPTY = "MODELTYPE_ECORE_EMPTY"
	public static final String MODELTYPE_ECORE_UNLOADABLE = "MODELTYPE_ECORE_UNLOADABLE"
	public static final String METAMODEL_ECORE_EMPTY = "METAMODEL_ECORE_EMPTY"
	public static final String METAMODEL_ECORE_UNLOADABLE = "METAMODEL_ECORE_EMPTY"
	public static final String METAMODEL_GENMODEL_UNLOADABLE = "METAMODEL_GENMODEL_UNLOADABLE"
	public static final String METAMODEL_GENMODEL_INFERRED = "METAMODEL_GENMODEL_INFERRED"
	public static final String METAMODEL_IMPLEMENTS_ERROR = "METAMODEL_IMPLEMENTS_ERROR"
	public static final String METAMODEL_EXACTTYPE_ERROR = "METAMODEL_EXACTTYPE_ERROR"
	public static final String METAMODEL_SELF_INHERITANCE = "METAMODEL_SELF_INHERITANCE"
	public static final String METAMODEL_XTEXT_SETUP = "METAMODEL_XTEXT_SETUP"
	public static final String ASPECT_NOT_FOUND = "METAMODEL_ASPECT_NOT_FOUND"
	public static final String INVALID_ASPECT_IMPORT = "INVALID_METAMODEL_ASPECT_IMPORT"
	public static final String ASPECT_NO_ANNOTATION = "METAMODEL_ASPECT_NO_ANNOTATION"
	public static final String MODELING_ELEMENT_ECORE_URI_INVALID = "MODELING_ELEMENT_ECORE_URI_INVALID"
	public static final String METAMODEL_NO_EMF_RUNTIME = "METAMODEL_NO_EMF_RUNTIME"
}
