/*
 * generated by Xtext
 */
package fr.inria.diverse.iot.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class IoTStandaloneSetup extends IoTStandaloneSetupGenerated{

	public static void doSetup() {
		new IoTStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

