/*
 * generated by Xtext
 */
package fr.inria.diverse.iot2;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IoT2RuntimeModule extends fr.inria.diverse.iot2.AbstractIoT2RuntimeModule {

}
