<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="compositestates" nsURI="http://compostestat/" nsPrefix="compositestates">
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eAnnotations source="required"/>
    <eOperations name="evalState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeState" eSuperTypes="//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1" eType="//State" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
