<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="joinpseudostate" nsURI="http://joinpseudostatemt/" nsPrefix="joinpseudostate">
  <eClassifiers xsi:type="ecore:EClass" name="Region">
    <eAnnotations source="extension"/>
    <eOperations name="findNewActiveTransitions">
      <eAnnotations source="aspect"/>
      <eParameters name="newActiveTransitions" upperBound="-1" eType="//Transition"/>
      <eParameters name="selectedTransition" eType="//Transition"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
    <eOperations name="findNewActiveStates">
      <eAnnotations source="aspect"/>
      <eParameters name="newActiveStates" upperBound="-1" eType="//AbstractState"/>
      <eParameters name="selectedTransition" eType="//Transition"/>
      <eParameters name="currentActiveTransitions" upperBound="-1" eType="//Transition"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
    <eOperations name="findOldActiveStates">
      <eAnnotations source="aspect"/>
      <eParameters name="oldActiveStates" upperBound="-1" eType="//AbstractState"/>
      <eParameters name="selectedTransition" eType="//Transition"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
    <eOperations name="_original_findNewActiveTransitions">
      <eAnnotations source="aspect"/>
      <eParameters name="newActiveTransitions" upperBound="-1" eType="//Transition"/>
      <eParameters name="selectedTransition" eType="//Transition"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
    <eOperations name="_original_findNewActiveStates">
      <eAnnotations source="aspect"/>
      <eParameters name="newActiveStates" upperBound="-1" eType="//AbstractState"/>
      <eParameters name="selectedTransition" eType="//Transition"/>
      <eParameters name="currentActiveTransitions" upperBound="-1" eType="//Transition"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
    <eOperations name="_original_findOldActiveStates">
      <eAnnotations source="aspect"/>
      <eParameters name="oldActiveStates" upperBound="-1" eType="//AbstractState"/>
      <eParameters name="selectedTransition" eType="//Transition"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractState" abstract="true">
    <eAnnotations source="extension"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1" eType="//Transition" eOpposite="//Transition/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1" eType="//Transition" eOpposite="//Transition/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pseudostate">
    <eAnnotations source="extension"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="//PseudostateKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eAnnotations source="extension"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="//AbstractState" eOpposite="//AbstractState/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//AbstractState" eOpposite="//AbstractState/incoming"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Hashtable" instanceClassName="java.util.Hashtable"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PseudostateKind">
    <eAnnotations source="extension"/>
    <eLiterals name="join" value="2">
      <eAnnotations source="addition"/>
    </eLiterals>
  </eClassifiers>
</ecore:EPackage>
