<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kmLogo"
    nsURI="http://www.kermeta.org/kmLogo" nsPrefix="kmlogo">
  <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="int"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="java.lang.Boolean"/>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  <eSubpackages name="ASM" nsURI="http://www.kermeta.org/kmLogo/ASM" nsPrefix="ASM">
    <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Primitive" abstract="true" eSuperTypes="#//ASM/Instruction"/>
    <eClassifiers xsi:type="ecore:EClass" name="Back" eSuperTypes="#//ASM/Primitive">
      <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1"
          eType="#//ASM/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Forward" eSuperTypes="#//ASM/Primitive">
      <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1"
          eType="#//ASM/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Left" eSuperTypes="#//ASM/Primitive">
      <eStructuralFeatures xsi:type="ecore:EReference" name="angle" eType="#//ASM/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Right" eSuperTypes="#//ASM/Primitive">
      <eStructuralFeatures xsi:type="ecore:EReference" name="angle" eType="#//ASM/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PenDown" eSuperTypes="#//ASM/Primitive"/>
    <eClassifiers xsi:type="ecore:EClass" name="PenUp" eSuperTypes="#//ASM/Primitive"/>
    <eClassifiers xsi:type="ecore:EClass" name="Clear" eSuperTypes="#//ASM/Primitive"/>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//ASM/Instruction"/>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryExp" abstract="true" eSuperTypes="#//ASM/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//ASM/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//ASM/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//ASM/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="integerValue" eType="#//Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProcCall" eSuperTypes="#//ASM/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="actualArgs" upperBound="-1"
          eType="#//ASM/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1"
          eType="#//ASM/ProcDeclaration" eOpposite="#//ASM/ProcDeclaration/procCall"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProcDeclaration" eSuperTypes="#//ASM/Instruction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1"
          eType="#//ASM/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="procCall" upperBound="-1"
          eType="#//ASM/ProcCall" eOpposite="#//ASM/ProcCall/declaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
          eType="#//ASM/Instruction" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//ASM/Instruction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
          eType="#//ASM/Instruction" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="#//ASM/ControlStructure">
      <eStructuralFeatures xsi:type="ecore:EReference" name="thenPart" lowerBound="1"
          eType="#//ASM/Block" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elsePart" eType="#//ASM/Block"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ControlStructure" eSuperTypes="#//ASM/Instruction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//ASM/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Repeat" eSuperTypes="#//ASM/ControlStructure">
      <eStructuralFeatures xsi:type="ecore:EReference" name="block" lowerBound="1"
          eType="#//ASM/Block" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="While" eSuperTypes="#//ASM/ControlStructure">
      <eStructuralFeatures xsi:type="ecore:EReference" name="block" lowerBound="1"
          eType="#//ASM/Block" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterCall" eSuperTypes="#//ASM/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//ASM/Parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Plus" eSuperTypes="#//ASM/BinaryExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="Minus" eSuperTypes="#//ASM/BinaryExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="Mult" eSuperTypes="#//ASM/BinaryExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="Div" eSuperTypes="#//ASM/BinaryExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="Equals" eSuperTypes="#//ASM/BinaryExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="Greater" eSuperTypes="#//ASM/BinaryExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="Lower" eSuperTypes="#//ASM/BinaryExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="LogoProgram">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
          eType="#//ASM/Instruction" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
