/*
 * generated by Xtext
 */
package fr.inria.diverse.iot2.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.inria.diverse.iot2.ui.internal.IoT2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IoT2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return IoT2Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return IoT2Activator.getInstance().getInjector(IoT2Activator.FR_INRIA_DIVERSE_IOT2_IOT2);
	}
	
}
