/*
 * generated by Xtext 2.31.0
 */
package fr.inria.diverse.melange.parser.antlr;

import com.google.inject.Inject;
import fr.inria.diverse.melange.parser.antlr.internal.InternalMelangeParser;
import fr.inria.diverse.melange.services.MelangeGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MelangeParser extends AbstractAntlrParser {

	@Inject
	private MelangeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMelangeParser createParser(XtextTokenStream stream) {
		return new InternalMelangeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ModelTypingSpace";
	}

	public MelangeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MelangeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
