/*
 * generated by Xtext
 */
package org.xtext.activitydiagram.input.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.activitydiagram.input.services.ActivityDiagramInputGrammarAccess;

public class ActivityDiagramInputParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ActivityDiagramInputGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.activitydiagram.input.parser.antlr.internal.InternalActivityDiagramInputParser createParser(XtextTokenStream stream) {
		return new org.xtext.activitydiagram.input.parser.antlr.internal.InternalActivityDiagramInputParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Input";
	}
	
	public ActivityDiagramInputGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ActivityDiagramInputGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
