/*
 * generated by Xtext
 */
package org.xtext.activitydiagram;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ActivityDiagramRuntimeModule extends org.xtext.activitydiagram.AbstractActivityDiagramRuntimeModule {

}
