<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="javaemftextprovided" nsURI="http://www.emftext.org/java/provided"
    nsPrefix="javaemftextprovided">
  <eClassifiers xsi:type="ecore:EClass" name="StatementListContainer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassMethod" eSuperTypes="#//StatementListContainer">
    <eOperations name="exec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conditional" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForLoop" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVariableStatement" eSuperTypes="#//Statement"/>
</ecore:EPackage>
