/*
 * generated by Xtext
 */
package fr.inria.diverse.k3.sle;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class K3SLERuntimeModule extends fr.inria.diverse.k3.sle.AbstractK3SLERuntimeModule {

}
