<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simpleconstraintslanguage" nsURI="http://simpleconstraintslanguage"
    nsPrefix="simpleconstraintslanguage">
  <eClassifiers xsi:type="ecore:EClass" name="Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelationalConstraint" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//CExpression"
        derived="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//CExpression"
        derived="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//CRelationalOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CExpression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CLiteral" abstract="true" eSuperTypes="#//CExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="CInteger" eSuperTypes="#//CLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CVarRef" eSuperTypes="#//CExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CRelationalOperator">
    <eLiterals name="equal"/>
    <eLiterals name="notEqual" value="1"/>
    <eLiterals name="greaterThan" value="2"/>
    <eLiterals name="lessThan" value="3"/>
  </eClassifiers>
</ecore:EPackage>
