<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="activitydiagram" nsURI="http://activitydiagram/1.0" nsPrefix="activitydiagram">
  <eClassifiers xsi:type="ecore:EClass" name="OpaqueAction" eSuperTypes="//Action">
    <eOperations name="execute">
      <eParameters name="c" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true" eSuperTypes="//ExecutableNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutableNode" abstract="true" eSuperTypes="//ActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode" abstract="true" eSuperTypes="//NamedElement">
    <eOperations name="execute">
      <eParameters name="c" eType="//Context"/>
    </eOperations>
    <eOperations name="terminate"/>
    <eOperations name="isReady">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="sendOffers">
      <eParameters name="tokens" upperBound="-1" eType="//Token"/>
    </eOperations>
    <eOperations name="takeOfferdTokens" upperBound="-1" eType="//Token"/>
    <eOperations name="addTokens">
      <eParameters name="tokens" upperBound="-1" eType="//Token"/>
    </eOperations>
    <eOperations name="hasOffers">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="removeToken">
      <eParameters name="token" eType="//Token"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1" eType="//ActivityEdge" eOpposite="//ActivityEdge/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1" eType="//ActivityEdge" eOpposite="//ActivityEdge/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1" eType="//Activity" eOpposite="//Activity/nodes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="running" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eOperations name="execute">
      <eParameters name="c" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Context" instanceClassName="org.modelexecution.operationalsemantics.gemoc.sequential.dynamic.Context"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge" abstract="true" eSuperTypes="//NamedElement">
    <eOperations name="sendOffer">
      <eParameters name="tokens" upperBound="-1" eType="//Token"/>
    </eOperations>
    <eOperations name="takeOfferedTokens" upperBound="-1" eType="//Token"/>
    <eOperations name="hasOffer">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="//ActivityNode" eOpposite="//ActivityNode/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//ActivityNode" eOpposite="//ActivityNode/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offers" upperBound="-1" eType="//Offer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Offer" instanceClassName="org.modelexecution.operationalsemantics.gemoc.sequential.dynamic.Offer"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Token" instanceClassName="org.modelexecution.operationalsemantics.gemoc.sequential.dynamic.Token"/>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="//NamedElement">
    <eOperations name="main">
      <eParameters name="value" upperBound="-1" eType="//InputValue"/>
    </eOperations>
    <eOperations name="execute">
      <eParameters name="c" eType="//Context"/>
    </eOperations>
    <eOperations name="reset"/>
    <eOperations name="writeToFile"/>
    <eOperations name="printTrace">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getIntegerVariableValue">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="variableName">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eOperations name="getBooleanVariableValue">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="variableName">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eOperations name="getVariableValue" eType="//Value">
      <eParameters name="variableName">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eOperations name="getVariable" eType="//Variable">
      <eParameters name="variableName">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eOperations name="writeTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1" eType="//ActivityNode" containment="true" eOpposite="//ActivityNode/activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1" eType="//ActivityEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locals" upperBound="-1" eType="//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1" eType="//Variable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true">
    <eOperations name="execute">
      <eParameters name="c" eType="//Context"/>
    </eOperations>
    <eOperations name="init">
      <eParameters name="c" eType="//Context"/>
    </eOperations>
    <eOperations name="print">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialValue" eType="//Value" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentValue" eType="//Value" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="//Value" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1" eType="//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true">
    <eOperations name="execute">
      <eParameters name="c" eType="//Context"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
