/*
 * generated by Xtext
 */
package fr.inria.diverse.k3.sle.ui.contentassist

import fr.inria.diverse.k3.sle.ui.contentassist.AbstractK3SLEProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class K3SLEProposalProvider extends AbstractK3SLEProposalProvider {
}
