<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lua" nsURI="http://luamt/" nsPrefix="lua">
  <eClassifiers xsi:type="ecore:EClass" name="Chunk">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="//Chunk">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1" eType="//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" eType="//LastStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LastStatement">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LastStatement_Return" eSuperTypes="//LastStatement">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LastStatement_Break" eSuperTypes="//LastStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Statement">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement_Block" eSuperTypes="//Statement">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement_While" eSuperTypes="//Statement">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement_Repeat" eSuperTypes="//Statement">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="//Block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement_If_Then_Else" eSuperTypes="//Statement">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifExpression" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifBlock" eType="//Block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseIf" upperBound="-1" eType="//Statement_If_Then_Else_ElseIfPart" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBlock" eType="//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement_If_Then_Else_ElseIfPart">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseifExpression" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseifBlock" eType="//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement_For_Numeric" eSuperTypes="//Statement">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iteratorName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startExpr" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="untilExpr" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stepExpr" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement_For_Generic" eSuperTypes="//Statement">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="names" unique="false" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement_GlobalFunction_Declaration" eSuperTypes="//Statement">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" unique="false" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="//Function" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement_LocalFunction_Declaration" eSuperTypes="//Statement">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="//Function" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement_Local_Variable_Declaration" eSuperTypes="//Statement">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableNames" unique="false" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialValue" upperBound="-1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement_FunctioncallOrAssignment" eSuperTypes="//Statement">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="//Statement_FunctioncallOrAssignment">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Nil" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_True" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_False" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Number" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_VarArgs" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_String" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Function" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="//Function" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_TableConstructor" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1" eType="//Field" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" unique="false" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varArgs">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Functioncall_Arguments">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field_AddEntryToTable_Brackets" eSuperTypes="//Field">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexExpression" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field_AddEntryToTable" eSuperTypes="//Field">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field_AppendEntryToTable" eSuperTypes="//Field">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LastStatement_ReturnWithValue" eSuperTypes="//LastStatement_Return">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnValues" upperBound="-1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement_Assignment" eSuperTypes="//Statement_FunctioncallOrAssignment">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement_CallMemberFunction" eSuperTypes="//Statement_FunctioncallOrAssignment">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memberFunctionName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="//Functioncall_Arguments" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement_CallFunction" eSuperTypes="//Statement_FunctioncallOrAssignment">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="//Functioncall_Arguments" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Or" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_And" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Larger" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Larger_Equal" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Smaller" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Smaller_Equal" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Equal" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Not_Equal" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Concatenation" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Plus" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Minus" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Multiplication" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Division" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Modulo" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Negate" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Length" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Invert" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_Exponentiation" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_CallMemberFunction" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memberFunctionName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="//Functioncall_Arguments" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_CallFunction" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="//Functioncall_Arguments" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_AccessArray" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="array" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_AccessMember" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memberName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression_VariableName" eSuperTypes="//Expression">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
      <eParameters name="c" eType="//Environment"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Environment">
    <eAnnotations source="aspect"/>
    <eOperations name="getVariable" eType="//Object">
      <eAnnotations source="aspect"/>
      <eParameters name="s">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eOperations name="pushValue">
      <eAnnotations source="aspect"/>
      <eParameters name="o" eType="//Object"/>
    </eOperations>
    <eOperations name="popValue" eType="//Object">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="putFunction">
      <eAnnotations source="aspect"/>
      <eParameters name="s">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
      <eParameters name="f" eType="//Function"/>
    </eOperations>
    <eOperations name="getFunction" eType="//Function">
      <eAnnotations source="aspect"/>
      <eParameters name="s">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eOperations name="putVariable">
      <eAnnotations source="aspect"/>
      <eParameters name="s">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
      <eParameters name="o" eType="//Object"/>
    </eOperations>
    <eOperations name="putAllVariables">
      <eAnnotations source="aspect"/>
      <eParameters name="v">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
      </eParameters>
    </eOperations>
    <eOperations name="putAllFunctions">
      <eAnnotations source="aspect"/>
      <eParameters name="f">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
      </eParameters>
    </eOperations>
    <eOperations name="pushAllValues">
      <eAnnotations source="aspect"/>
      <eParameters name="v" eType="//Stack"/>
    </eOperations>
    <eOperations name="getValues" eType="//Stack">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="getVariables">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eOperations name="getFunctions">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="//Environment">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Object" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Stack" instanceClassName="java.util.Stack"/>
</ecore:EPackage>
