/*
 * generated by Xtext
 */
package fr.inria.diverse.iot2.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.inria.diverse.iot2.services.IoT2GrammarAccess;

public class IoT2Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private IoT2GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.inria.diverse.iot2.parser.antlr.internal.InternalIoT2Parser createParser(XtextTokenStream stream) {
		return new fr.inria.diverse.iot2.parser.antlr.internal.InternalIoT2Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "System";
	}
	
	public IoT2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(IoT2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
