<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="iot2" nsURI="http://iot2-melange/" nsPrefix="iot2">
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//HWComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boards" upperBound="-1"
        eType="#//Board" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sketch" eType="#//Sketch"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Board">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//BoardType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//HWComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sketch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//Activity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HWComponent" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//OperationDef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//HWComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" eSuperTypes="#//HWComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperationDef"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BoardType">
    <eLiterals name="RaspberryPi"/>
    <eLiterals name="Arduino" value="1"/>
    <eLiterals name="BeagleBoard" value="2"/>
  </eClassifiers>
</ecore:EPackage>
