/*
 * generated by Xtext
 */
package fr.inria.diverse.iot.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.inria.diverse.iot.xtext.ui.internal.IoTActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IoTExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return IoTActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return IoTActivator.getInstance().getInjector(IoTActivator.FR_INRIA_DIVERSE_IOT_XTEXT_IOT);
	}
	
}
