/**
 *
 * $Id$
 */
package org.csu.idl.idlmm.validation;

import org.csu.idl.idlmm.Container;

/**
 * A sample validator interface for {@link org.csu.idl.idlmm.Contained}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContainedValidator {
	boolean validate();

	boolean validateRepositoryId(String value);
	boolean validateVersion(String value);
	boolean validateAbsoluteName(String value);
	boolean validateDefinedIn(Container value);
}
