/**
 *
 * $Id$
 */
package org.csu.idl.idlmm.validation;

import org.csu.idl.idlmm.ExceptionDef;
import org.csu.idl.idlmm.ParameterDef;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.csu.idl.idlmm.OperationDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperationDefValidator {
	boolean validate();

	boolean validateParameters(EList<ParameterDef> value);
	boolean validateIsOneway(boolean value);
	boolean validateContexts(EList<String> value);
	boolean validateCanRaise(EList<ExceptionDef> value);
}
