/*
 * generated by Xtext 2.31.0
 */
package fr.inria.diverse.melange.ui.tests;

import com.google.inject.Injector;
import fr.inria.diverse.melange.ui.internal.MelangeActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MelangeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MelangeActivator.getInstance().getInjector("fr.inria.diverse.melange.Melange");
	}

}
