/*
 * generated by Xtext
 */
package fr.inria.diverse.iot2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class IoT2UiModule extends fr.inria.diverse.iot2.ui.AbstractIoT2UiModule {
	public IoT2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
