/*
 * generated by Xtext 2.9.2
 */
package fr.inria.diverse.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMiniFSMScopeProvider extends DelegatingScopeProvider {
}
