<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="puzzle" nsURI="http://www.inria.fr/diverse/puzzle" nsPrefix="puzzle">
  <eClassifiers xsi:type="ecore:EClass" name="Composition" eSuperTypes="../../fr.inria.diverse.melange.metamodel/model/Melange.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="VarDecl" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageRef" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="ecore:EClass ../../fr.inria.diverse.melange.metamodel/model/Melange.ecore#//Metamodel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarRef" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//VarDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregation" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiring" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providing" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Extension" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extension" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
