<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ifinitestatemachines" nsURI="http://fr.inria.diverse.examples.ifsm" nsPrefix="ifinitestatemachines">
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eOperations name="eval">
      <eParameters name="context">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eParameters>
      <eParameters name="output">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
