/*
 * generated by Xtext
 */
package org.modelexecution.operationalsemantics;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ActivityDiagramStandaloneSetup extends ActivityDiagramStandaloneSetupGenerated{

	public static void doSetup() {
		new ActivityDiagramStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

