/*
 * generated by Xtext 2.27.0
 */
package fr.inria.diverse.melange


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MelangeStandaloneSetup extends MelangeStandaloneSetupGenerated {

	def static void doSetup() {
		new MelangeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
