<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore" nsURI="http://multiplicities/" nsPrefix="ecore">
  <eClassifiers xsi:type="ecore:EClass" name="EAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAttributeType" upperBound="5"
        eType="#//EDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAttributes" lowerBound="5"
        upperBound="15" eType="#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eIDAttribute" lowerBound="1"
        upperBound="-1" eType="#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="EPackage"/>
</ecore:EPackage>
