<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fsm" nsURI="http://fsm/" nsPrefix="fsm">
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eOperations name="foo" eType="//Object">
      <eParameters name="arg1" eType="//A"/>
      <eParameters name="arg2" eType="//C"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="a" unique="false" eType="//A"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="b" unique="false" upperBound="-1" eType="//B"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="c" unique="false" eType="//C"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="A" instanceClassName="fr.inria.diverse.melange.tests.aspects.fsm.A"/>
  <eClassifiers xsi:type="ecore:EEnum" name="C">
    <eLiterals name="X"/>
    <eLiterals name="Y"/>
    <eLiterals name="Z"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="B" instanceClassName="fr.inria.diverse.melange.tests.aspects.fsm.B"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Object" instanceClassName="java.lang.Object"/>
</ecore:EPackage>
