<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fsm" nsURI="http://fsm/" nsPrefix="fsm">
  <eClassifiers xsi:type="ecore:EClass" name="FSM">
    <eStructuralFeatures xsi:type="ecore:EReference" name="s" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="f" eType="#//FSM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State"/>
</ecore:EPackage>
