/*
 * generated by Xtext
 */
package org.xtext.activitydiagram.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.activitydiagram.services.ActivityDiagramGrammarAccess;

public class ActivityDiagramParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ActivityDiagramGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.activitydiagram.parser.antlr.internal.InternalActivityDiagramParser createParser(XtextTokenStream stream) {
		return new org.xtext.activitydiagram.parser.antlr.internal.InternalActivityDiagramParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Activity";
	}
	
	public ActivityDiagramGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ActivityDiagramGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
