/*
 * generated by Xtext
 */
package fr.inria.diverse.melange;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MelangeRuntimeModule extends fr.inria.diverse.melange.AbstractMelangeRuntimeModule {

}
