<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CompleteFSMrequired" nsURI="http://CompleteFSMrequired" nsPrefix="CompleteFSMrequired"/>
