/*
 * generated by Xtext
 */
package org.xtext.activitydiagram.input;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ActivityDiagramInputStandaloneSetup extends ActivityDiagramInputStandaloneSetupGenerated{

	public static void doSetup() {
		new ActivityDiagramInputStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

