/*
 * generated by Xtext 2.9.2
 */
package fr.inria.diverse.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MiniFSMProposalProvider extends AbstractMiniFSMProposalProvider {
}
