/*
 * generated by Xtext
 */
package fr.inria.diverse.iot.xtext.ui.contentassist

import fr.inria.diverse.iot.xtext.ui.contentassist.AbstractIoTProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class IoTProposalProvider extends AbstractIoTProposalProvider {
}
